export const GET_UNIVERSITIES_LIST = 'GET_UNIVERSITIES_LIST';
export const GET_UNIVERSITIES_SUCCESS = 'GET_UNIVERSITIES_SUCCESS';
export const GET_UNIVERSITIES_FAIL = 'GET_UNIVERSITIES_FAIL';
export const SET_PAGINATION_META_DATA = 'SET_PAGINATION_META_DATA';
export const GET_UNIVERSITY_DETAILS = 'GET_UNIVERSITY_DETAILS';
export const SET_UNIVERSITY_DETAILS = 'SET_UNIVERSITY_DETAILS';
export const SHOW_LODER = 'SHOW_LODER';
export const HIDE_LODER = 'HIDE_LODER';
export const RESET_STORE = 'RESET_STORE';

